const mongoose = require('mongoose');
const dotenv = require('dotenv');
const bcrypt = require('bcryptjs');

dotenv.config({ path: './.env' });

const User = require('./models/User');
const Product = require('./models/Product');
const Category = require('./models/Category');
const Order = require('./models/Order');
const Cart = require('./models/Cart');
const Wishlist = require('./models/Wishlist');
const Coupon = require('./models/Coupon');

const connectDB = require('./config/db');

const seedData = async () => {
  try {
    if (mongoose.connection.readyState !== 1) {
      await connectDB();
    }

    // Clear existing data
    await Promise.all([
      User.deleteMany({}),
      Product.deleteMany({}),
      Category.deleteMany({}),
      Order.deleteMany({}),
      Cart.deleteMany({}),
      Wishlist.deleteMany({}),
      Coupon.deleteMany({}),
    ]);

    console.log('Cleared existing data'.yellow);

    // Create Admin User
    const admin = await User.create({
      name: 'Admin',
      email: 'admin@shophub.com',
      password: 'Admin@123',
      phone: '9876543210',
      role: 'admin',
      isVerified: true,
    });
    console.log('Admin created: admin@shophub.com / Admin@123'.green);

    // Create Test User
    const user = await User.create({
      name: 'Test User',
      email: 'user@shophub.com',
      password: 'User@123',
      phone: '9876543211',
      role: 'user',
      isVerified: true,
    });
    console.log('User created: user@shophub.com / User@123'.green);

    // Create Categories
    const categories = await Category.create([
      {
        name: 'Electronics',
        description: 'Latest gadgets and electronic devices',
        icon: 'Smartphone',
        order: 1,
        isActive: true,
      },
      {
        name: 'Fashion',
        description: 'Trendy clothing and accessories',
        icon: 'Shirt',
        order: 2,
        isActive: true,
      },
      {
        name: 'Home & Kitchen',
        description: 'Everything for your home',
        icon: 'Home',
        order: 3,
        isActive: true,
      },
      {
        name: 'Books',
        description: 'Books across all genres',
        icon: 'Book',
        order: 4,
        isActive: true,
      },
      {
        name: 'Sports & Fitness',
        description: 'Sports equipment and fitness gear',
        icon: 'Trophy',
        order: 5,
        isActive: true,
      },
      {
        name: 'Beauty & Personal Care',
        description: 'Beauty products and personal care items',
        icon: 'Sparkles',
        order: 6,
        isActive: true,
      },
      {
        name: 'Toys & Games',
        description: 'Fun toys and board games',
        icon: 'Gamepad2',
        order: 7,
        isActive: true,
      },
      {
        name: 'Automotive',
        description: 'Car accessories and automotive parts',
        icon: 'Car',
        order: 8,
        isActive: true,
      },
    ]);
    console.log(`${categories.length} categories created`.green);

    // Create Subcategories
    const electronicsSubs = await Category.create([
      { name: 'Mobile Phones', parent: categories[0]._id, order: 1, isActive: true },
      { name: 'Laptops', parent: categories[0]._id, order: 2, isActive: true },
      { name: 'Headphones', parent: categories[0]._id, order: 3, isActive: true },
      { name: 'Cameras', parent: categories[0]._id, order: 4, isActive: true },
      { name: 'Smart Watches', parent: categories[0]._id, order: 5, isActive: true },
    ]);

    const fashionSubs = await Category.create([
      { name: 'Men\'s Clothing', parent: categories[1]._id, order: 1, isActive: true },
      { name: 'Women\'s Clothing', parent: categories[1]._id, order: 2, isActive: true },
      { name: 'Kids Wear', parent: categories[1]._id, order: 3, isActive: true },
      { name: 'Footwear', parent: categories[1]._id, order: 4, isActive: true },
      { name: 'Accessories', parent: categories[1]._id, order: 5, isActive: true },
    ]);

    // Update parent categories with subcategories
    await Category.findByIdAndUpdate(categories[0]._id, {
      $push: { subcategories: { $each: electronicsSubs.map(s => s._id) } },
    });
    await Category.findByIdAndUpdate(categories[1]._id, {
      $push: { subcategories: { $each: fashionSubs.map(s => s._id) } },
    });

    // Create Products
    const rawProducts = [
      // === ELECTRONICS - Mobile Phones ===
      {
        name: 'iPhone 15 Pro Max 256GB - Natural Titanium',
        description: 'The most powerful iPhone ever. A17 Pro chip, 48MP camera system with 5x optical zoom, titanium design, and all-day battery life. Features a stunning 6.7-inch Super Retina XDR display with ProMotion technology.',
        features: ['A17 Pro Chip', '48MP Main Camera', '5x Optical Zoom', 'Titanium Design', 'USB-C'],
        specifications: [
          { key: 'Display', value: '6.7" Super Retina XDR' },
          { key: 'Processor', value: 'A17 Pro' },
          { key: 'Storage', value: '256GB' },
          { key: 'RAM', value: '8GB' },
          { key: 'Battery', value: '4422mAh' },
          { key: 'OS', value: 'iOS 17' },
        ],
        price: 139900,
        originalPrice: 159900,
        stock: 50,
        sku: 'IPH-15PM-256-NT',
        barcode: '8901234567890',
        category: electronicsSubs[0]._id,
        brand: 'Apple',
        images: [
          { public_id: 'seed/iphone-15-pro-max-front', url: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-15-pro-max-naturaltitanium-select?wid=940&hei=1112&fmt=png-alpha&.v=1697203752456', isPrimary: true },
          { public_id: 'seed/iphone-15-pro-max-back', url: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-15-pro-max-naturaltitanium-back?wid=940&hei=1112&fmt=png-alpha&.v=1697203752456' },
        ],
        colors: [{ name: 'Natural Titanium', hex: '#8B8B8B', stock: 20 }, { name: 'Blue Titanium', hex: '#4A5D6B', stock: 15 }, { name: 'White Titanium', hex: '#F5F5F0', stock: 15 }],
        sizes: [{ name: '256GB', stock: 50, priceModifier: 0 }, { name: '512GB', stock: 30, priceModifier: 15000 }, { name: '1TB', stock: 10, priceModifier: 30000 }],
        ratings: 4.8,
        numReviews: 1256,
        isFeatured: true,
        isTrending: true,
        isBestSeller: true,
        isNewArrival: true,
        freeDelivery: true,
        tags: ['iphone', 'apple', 'smartphone', 'premium', '5g'],
        sellCount: 5000,
      },
      {
        name: 'Samsung Galaxy S24 Ultra 512GB',
        description: 'Galaxy AI is here. Built with titanium, Galaxy S24 Ultra features a flat display with Corning Gorilla Armor, 200MP camera with AI processing, and the built-in S Pen. Powered by the Snapdragon 8 Gen 3 processor.',
        features: ['Galaxy AI', '200MP Camera', 'S Pen Included', 'Titanium Frame', 'Snapdragon 8 Gen 3'],
        specifications: [
          { key: 'Display', value: '6.8" Dynamic AMOLED 2X' },
          { key: 'Processor', value: 'Snapdragon 8 Gen 3' },
          { key: 'Storage', value: '512GB' },
          { key: 'RAM', value: '12GB' },
          { key: 'Battery', value: '5000mAh' },
          { key: 'OS', value: 'Android 14' },
        ],
        price: 124999,
        originalPrice: 134999,
        stock: 40,
        sku: 'S24U-512-BK',
        barcode: '8901234567891',
        category: electronicsSubs[0]._id,
        brand: 'Samsung',
        images: [
          { url: 'https://images.samsung.com/is/image/samsung/p6pim/in/2401/gallery/in-galaxy-s24-s928-491354-sm-s928bztcins-thumb-539320540?wid=480', isPrimary: true },
        ],
        colors: [{ name: 'Titanium Black', hex: '#1A1A1A', stock: 20 }, { name: 'Titanium Gray', hex: '#808080', stock: 10 }, { name: 'Titanium Violet', hex: '#8B5CF6', stock: 10 }],
        ratings: 4.7,
        numReviews: 892,
        isFeatured: true,
        isTrending: true,
        isBestSeller: true,
        freeDelivery: true,
        tags: ['samsung', 'galaxy', 'android', 'smartphone', '5g'],
        sellCount: 3500,
      },
      {
        name: 'OnePlus 12 5G 256GB',
        description: 'OnePlus 12 features the Snapdragon 8 Gen 3 processor, a 50MP Sony LYT-808 main camera with Hasselblad tuning, 100W SUPERVOOC charging, and a stunning 2K 120Hz ProXDR display.',
        features: ['Snapdragon 8 Gen 3', 'Hasselblad Camera', '100W Charging', '2K 120Hz Display', 'IP65 Rating'],
        specifications: [
          { key: 'Display', value: '6.82" 2K 120Hz ProXDR' },
          { key: 'Processor', value: 'Snapdragon 8 Gen 3' },
          { key: 'Storage', value: '256GB' },
          { key: 'RAM', value: '16GB' },
          { key: 'Battery', value: '5400mAh' },
          { key: 'OS', value: 'OxygenOS 14' },
        ],
        price: 69999,
        originalPrice: 74999,
        stock: 60,
        sku: 'OP12-256-FG',
        barcode: '8901234567892',
        category: electronicsSubs[0]._id,
        brand: 'OnePlus',
        images: [
          { url: 'https://oasis.opstatics.com/content/dam/oasis/page/2024/oneplus-12/specs/OnePlus-12-green.png', isPrimary: true },
        ],
        colors: [{ name: 'Flowy Emerald', hex: '#2E8B57', stock: 25 }, { name: 'Silky Black', hex: '#1C1C1C', stock: 20 }],
        ratings: 4.6,
        numReviews: 567,
        isFeatured: true,
        isNewArrival: true,
        freeDelivery: true,
        tags: ['oneplus', 'smartphone', '5g', 'flagship'],
        sellCount: 2100,
      },

      // === ELECTRONICS - Laptops ===
      {
        name: 'MacBook Pro 16" M3 Max 36GB/1TB',
        description: 'Supercharged by M3 Max chip with up to 128GB unified memory. Stunning 16-inch Liquid Retina XDR display. Up to 22 hours of battery life. Advanced camera and audio. Thunderbolt 4 ports.',
        features: ['M3 Max Chip', '36GB Unified Memory', '1TB SSD', '22hr Battery', 'Liquid Retina XDR'],
        specifications: [
          { key: 'Processor', value: 'Apple M3 Max' },
          { key: 'Memory', value: '36GB Unified' },
          { key: 'Storage', value: '1TB SSD' },
          { key: 'Display', value: '16.2" Liquid Retina XDR' },
          { key: 'Battery', value: 'Up to 22 hours' },
          { key: 'Weight', value: '2.14 kg' },
        ],
        price: 349900,
        originalPrice: 399900,
        stock: 20,
        sku: 'MBP-M3M-36-1TB',
        barcode: '8901234567893',
        category: electronicsSubs[1]._id,
        brand: 'Apple',
        images: [
          { url: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/mbp16-spaceblack-select-202310?wid=904&hei=840&fmt=jpeg&qlt=90&.v=1697311054548', isPrimary: true },
        ],
        colors: [{ name: 'Space Black', hex: '#2C2C2E', stock: 10 }, { name: 'Silver', hex: '#E0E0E0', stock: 10 }],
        ratings: 4.9,
        numReviews: 345,
        isFeatured: true,
        isBestSeller: true,
        freeDelivery: true,
        tags: ['macbook', 'apple', 'laptop', 'pro', 'm3'],
        sellCount: 1200,
      },
      {
        name: 'ASUS ROG Zephyrus G16 Gaming Laptop',
        description: 'Ultra-slim gaming laptop with Intel Core i9-13900H, NVIDIA RTX 4070, 16GB DDR5, 1TB SSD, and a 16-inch QHD 240Hz display. Premium build with RGB keyboard.',
        features: ['Intel i9-13900H', 'RTX 4070 8GB', '16GB DDR5', '1TB SSD', '240Hz Display'],
        specifications: [
          { key: 'Processor', value: 'Intel Core i9-13900H' },
          { key: 'GPU', value: 'NVIDIA RTX 4070 8GB' },
          { key: 'Memory', value: '16GB DDR5' },
          { key: 'Storage', value: '1TB NVMe SSD' },
          { key: 'Display', value: '16" QHD 240Hz' },
          { key: 'Weight', value: '1.9 kg' },
        ],
        price: 189990,
        originalPrice: 209990,
        stock: 15,
        sku: 'ROG-G16-I9-4070',
        barcode: '8901234567894',
        category: electronicsSubs[1]._id,
        brand: 'ASUS',
        images: [
          { url: 'https://dlcdnwebimgs.asus.com/gain/9F3E5E2C-0B5A-4B5C-8B5A-5C5E5F5A5B5C/w800', isPrimary: true },
        ],
        ratings: 4.5,
        numReviews: 234,
        isTrending: true,
        tags: ['gaming', 'laptop', 'asus', 'rog', 'rtx'],
        sellCount: 800,
      },

      // === ELECTRONICS - Headphones ===
      {
        name: 'Sony WH-1000XM5 Wireless Noise Cancelling',
        description: 'Industry-leading noise cancellation with Auto NC Optimizer. Crystal clear hands-free calling with 4 beamforming microphones. 30-hour battery life. Exceptional comfort with lightweight design.',
        features: ['Industry-leading ANC', '30hr Battery', 'Multipoint Connection', 'Hi-Res Audio', 'Speak-to-Chat'],
        specifications: [
          { key: 'Type', value: 'Over-Ear Wireless' },
          { key: 'Driver', value: '30mm' },
          { key: 'Battery', value: '30 hours' },
          { key: 'Charging', value: 'USB-C, 3.5mm' },
          { key: 'Weight', value: '250g' },
          { key: 'Codec', value: 'LDAC, AAC, SBC' },
        ],
        price: 29990,
        originalPrice: 34990,
        stock: 80,
        sku: 'WH-1000XM5-BK',
        barcode: '8901234567895',
        category: electronicsSubs[2]._id,
        brand: 'Sony',
        images: [
          { url: 'https://www.sony.co.in/image/5d9f9c8e8a0b4c5f8e7a6b5c4d3e2f1a?fmt=pjpeg&wid=660&bgcolor=FFFFFF&bgc=FFFFFF', isPrimary: true },
        ],
        colors: [{ name: 'Black', hex: '#000000', stock: 40 }, { name: 'Silver', hex: '#C0C0C0', stock: 25 }, { name: 'Midnight Blue', hex: '#191970', stock: 15 }],
        ratings: 4.7,
        numReviews: 1890,
        isFeatured: true,
        isBestSeller: true,
        freeDelivery: true,
        tags: ['sony', 'headphones', 'noise cancelling', 'wireless', 'premium'],
        sellCount: 8000,
      },
      {
        name: 'AirPods Pro 2nd Generation USB-C',
        description: 'Adaptive Audio. Active Noise Cancellation up to 2x more effective. Personalized Spatial Audio. USB-C charging case with Find My and speaker.',
        features: ['Adaptive Audio', 'Active Noise Cancellation', 'Personalized Spatial Audio', 'USB-C', 'IPX4 Sweat Resistant'],
        specifications: [
          { key: 'Type', value: 'In-Ear Wireless' },
          { key: 'Chip', value: 'H2' },
          { key: 'Battery', value: '6hr (30hr with case)' },
          { key: 'Charging', value: 'USB-C, MagSafe, Qi' },
          { key: 'Water Resistance', value: 'IPX4' },
          { key: 'Weight', value: '5.3g per earbud' },
        ],
        price: 24900,
        originalPrice: 26900,
        stock: 100,
        sku: 'APP-AIRPODS-PRO2-USB-C',
        barcode: '8901234567896',
        category: electronicsSubs[2]._id,
        brand: 'Apple',
        images: [
          { url: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/MTJV3?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1694014871985', isPrimary: true },
        ],
        ratings: 4.8,
        numReviews: 2340,
        isFeatured: true,
        isBestSeller: true,
        isNewArrival: true,
        freeDelivery: true,
        tags: ['airpods', 'apple', 'earphones', 'wireless', 'anc'],
        sellCount: 12000,
      },

      // === ELECTRONICS - Smart Watches ===
      {
        name: 'Apple Watch Ultra 2 49mm',
        description: 'The most rugged and capable Apple Watch ever. 49mm titanium case, precision dual-frequency GPS, Action button, 36-hour battery life, and the brightest display ever on an Apple Watch.',
        features: ['49mm Titanium Case', 'Precision GPS', 'Action Button', '36hr Battery', '3000 nits Display'],
        specifications: [
          { key: 'Display', value: '49mm, 3000 nits' },
          { key: 'Processor', value: 'S9 SiP' },
          { key: 'Battery', value: '36 hours' },
          { key: 'Water Resistance', value: 'WR100, EN13319' },
          { key: 'Connectivity', value: 'LTE, Bluetooth 5.3, WiFi' },
          { key: 'Sensors', value: 'Heart Rate, SpO2, Temperature' },
        ],
        price: 89900,
        originalPrice: 94900,
        stock: 30,
        sku: 'AW-ULTRA2-49-OR',
        barcode: '8901234567897',
        category: electronicsSubs[4]._id,
        brand: 'Apple',
        images: [
          { url: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/MQDT3ref_VW_34FR+watch-49-titanium-ultra2_VW_34FR_WF_CO?wid=1400&hei=1400&fmt=jpeg&qlt=90&.v=1694501549487', isPrimary: true },
        ],
        colors: [{ name: 'Orange Alpine', hex: '#FF6B35', stock: 10 }, { name: 'Green Trail', hex: '#2E8B57', stock: 10 }, { name: 'Blue Ocean', hex: '#006994', stock: 10 }],
        ratings: 4.8,
        numReviews: 456,
        isFeatured: true,
        isNewArrival: true,
        freeDelivery: true,
        tags: ['apple watch', 'smartwatch', 'fitness', 'premium', 'gps'],
        sellCount: 1500,
      },

      // === FASHION - Men's Clothing ===
      {
        name: 'Premium Cotton Slim Fit Casual Shirt',
        description: 'Elevate your style with this premium 100% cotton slim fit shirt. Features a modern cut, spread collar, and mother-of-pearl buttons. Perfect for both casual and semi-formal occasions.',
        features: ['100% Premium Cotton', 'Slim Fit', 'Spread Collar', 'Mother-of-Pearl Buttons', 'Machine Washable'],
        specifications: [
          { key: 'Material', value: '100% Cotton' },
          { key: 'Fit', value: 'Slim Fit' },
          { key: 'Collar', value: 'Spread Collar' },
          { key: 'Care', value: 'Machine Wash' },
          { key: 'Origin', value: 'Made in India' },
        ],
        price: 1999,
        originalPrice: 3999,
        stock: 200,
        sku: 'CT-SLIM-SHIRT-BL',
        barcode: '8901234567898',
        category: fashionSubs[0]._id,
        brand: 'Peter England',
        images: [
          { url: 'https://assets.ajio.com/medias/sys_master/root/20231012/1NfM/6527f0d1ddfb151f2e6b5c1e/-473Wx593H-466343321-blue-MODEL.jpg', isPrimary: true },
        ],
        colors: [{ name: 'Sky Blue', hex: '#87CEEB', stock: 50 }, { name: 'White', hex: '#FFFFFF', stock: 50 }, { name: 'Black', hex: '#000000', stock: 40 }, { name: 'Navy', hex: '#000080', stock: 60 }],
        sizes: [{ name: 'S', stock: 40 }, { name: 'M', stock: 60 }, { name: 'L', stock: 60 }, { name: 'XL', stock: 30 }, { name: 'XXL', stock: 10 }],
        ratings: 4.3,
        numReviews: 2340,
        isBestSeller: true,
        freeDelivery: true,
        tags: ['shirt', 'cotton', 'formal', 'casual', 'men'],
        sellCount: 15000,
      },
      {
        name: 'Classic Fit Blazer - Navy Blue',
        description: 'A timeless navy blue blazer crafted from premium wool-blend fabric. Features notch lapels, two-button closure, and interior pockets. Perfect for weddings, business meetings, and formal events.',
        features: ['Wool-Blend Fabric', 'Notch Lapels', 'Two-Button Closure', 'Interior Pockets', 'Fully Lined'],
        specifications: [
          { key: 'Material', value: '70% Wool, 30% Polyester' },
          { key: 'Fit', value: 'Classic Fit' },
          { key: 'Closure', value: 'Two-Button' },
          { key: 'Lapels', value: 'Notch Lapels' },
          { key: 'Care', value: 'Dry Clean Only' },
        ],
        price: 8999,
        originalPrice: 14999,
        stock: 50,
        sku: 'BLZ-CLASSIC-NVY',
        barcode: '8901234567899',
        category: fashionSubs[0]._id,
        brand: 'Louis Philippe',
        images: [
          { url: 'https://assets.ajio.com/medias/sys_master/root/20230615/1NfM/648a9e42ddfb151f2e6b5c1e/-473Wx593H-466343321-blue-MODEL.jpg', isPrimary: true },
        ],
        sizes: [{ name: '38', stock: 10 }, { name: '40', stock: 15 }, { name: '42', stock: 15 }, { name: '44', stock: 10 }],
        ratings: 4.5,
        numReviews: 567,
        isFeatured: true,
        tags: ['blazer', 'formal', 'wool', 'premium', 'men'],
        sellCount: 2500,
      },

      // === FASHION - Women's Clothing ===
      {
        name: 'Floral Print Maxi Dress',
        description: 'Beautiful floral print maxi dress with a flattering A-line silhouette. Features adjustable spaghetti straps, a smocked back for comfort, and side pockets. Perfect for summer days and beach vacations.',
        features: ['Floral Print', 'A-Line Silhouette', 'Adjustable Straps', 'Smocked Back', 'Side Pockets'],
        specifications: [
          { key: 'Material', value: '100% Rayon' },
          { key: 'Length', value: 'Maxi' },
          { key: 'Neckline', value: 'V-Neck' },
          { key: 'Care', value: 'Machine Wash Cold' },
          { key: 'Fit', value: 'True to Size' },
        ],
        price: 2499,
        originalPrice: 4999,
        stock: 150,
        sku: 'MAXI-FLORAL-PK',
        barcode: '8901234567900',
        category: fashionSubs[1]._id,
        brand: 'AND',
        images: [
          { url: 'https://assets.ajio.com/medias/sys_master/root/20230615/1NfM/648a9e42ddfb151f2e6b5c1e/-473Wx593H-466343321-blue-MODEL.jpg', isPrimary: true },
        ],
        colors: [{ name: 'Pink Floral', hex: '#FFB6C1', stock: 40 }, { name: 'Blue Floral', hex: '#87CEEB', stock: 40 }, { name: 'Yellow Floral', hex: '#FFD700', stock: 30 }],
        sizes: [{ name: 'XS', stock: 20 }, { name: 'S', stock: 40 }, { name: 'M', stock: 40 }, { name: 'L', stock: 30 }, { name: 'XL', stock: 20 }],
        ratings: 4.4,
        numReviews: 1234,
        isBestSeller: true,
        freeDelivery: true,
        tags: ['dress', 'maxi', 'floral', 'summer', 'women'],
        sellCount: 8000,
      },
      {
        name: 'Premium Leather Handbag - Tote Bag',
        description: 'Luxurious genuine leather tote bag with gold-toned hardware. Features a spacious main compartment, interior zip pocket, and detachable shoulder strap. Perfect for everyday elegance.',
        features: ['Genuine Leather', 'Gold Hardware', 'Detachable Strap', 'Interior Pockets', 'Magnetic Closure'],
        specifications: [
          { key: 'Material', value: '100% Genuine Leather' },
          { key: 'Dimensions', value: '35cm x 28cm x 12cm' },
          { key: 'Closure', value: 'Magnetic Snap' },
          { key: 'Strap', value: 'Detachable, 110cm' },
          { key: 'Hardware', value: 'Gold-Toned' },
        ],
        price: 12999,
        originalPrice: 19999,
        stock: 40,
        sku: 'LTHR-TOTE-BRN',
        barcode: '8901234567901',
        category: fashionSubs[4]._id,
        brand: 'Lavie',
        images: [
          { url: 'https://assets.ajio.com/medias/sys_master/root/20230615/1NfM/648a9e42ddfb151f2e6b5c1e/-473Wx593H-466343321-blue-MODEL.jpg', isPrimary: true },
        ],
        colors: [{ name: 'Tan Brown', hex: '#D2691E', stock: 15 }, { name: 'Black', hex: '#000000', stock: 15 }, { name: 'Burgundy', hex: '#800020', stock: 10 }],
        ratings: 4.6,
        numReviews: 789,
        isFeatured: true,
        tags: ['handbag', 'leather', 'tote', 'premium', 'women'],
        sellCount: 3200,
      },

      // === FASHION - Footwear ===
      {
        name: 'Air Max 270 React - Running Shoes',
        description: 'Nike Air Max 270 React combines the huge Air unit at the heel with Nike React foam for ultimate comfort. The mesh upper is lightweight and breathable, perfect for running and casual wear.',
        features: ['Air Max 270 Heel Unit', 'Nike React Foam', 'Breathable Mesh', 'Rubber Outsole', 'Padded Collar'],
        specifications: [
          { key: 'Upper', value: 'Engineered Mesh' },
          { key: 'Midsole', value: 'Nike React + Air Max' },
          { key: 'Outsole', value: 'Rubber' },
          { key: 'Closure', value: 'Lace-Up' },
          { key: 'Weight', value: '340g' },
        ],
        price: 14995,
        originalPrice: 18995,
        stock: 100,
        sku: 'NK-AM270-REACT-BW',
        barcode: '8901234567902',
        category: fashionSubs[3]._id,
        brand: 'Nike',
        images: [
          { url: 'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/9d1f8a3b-8c4a-4e8a-9b5a-2e5a8b3c4d5e/air-max-270-react-shoes.png', isPrimary: true },
        ],
        colors: [{ name: 'Black/White', hex: '#000000', stock: 30 }, { name: 'White/Red', hex: '#FFFFFF', stock: 25 }, { name: 'Blue/Orange', hex: '#0000FF', stock: 20 }],
        sizes: [{ name: '7', stock: 15 }, { name: '8', stock: 20 }, { name: '9', stock: 25 }, { name: '10', stock: 20 }, { name: '11', stock: 15 }, { name: '12', stock: 5 }],
        ratings: 4.5,
        numReviews: 3456,
        isBestSeller: true,
        isTrending: true,
        freeDelivery: true,
        tags: ['nike', 'shoes', 'running', 'air max', 'sneakers'],
        sellCount: 20000,
      },

      // === HOME & KITCHEN ===
      {
        name: 'Premium Non-Stick Cookware Set (10-Piece)',
        description: 'Complete 10-piece cookware set with premium non-stick coating. Includes fry pans, saucepans, a Dutch oven, and lids. Suitable for all stovetops including induction. Ergonomic handles stay cool.',
        features: ['Premium Non-Stick', '10-Piece Set', 'Induction Compatible', 'Cool-Touch Handles', 'Dishwasher Safe'],
        specifications: [
          { key: 'Material', value: 'Hard-Anodized Aluminum' },
          { key: 'Coating', value: '3-Layer Non-Stick' },
          { key: 'Pieces', value: '10' },
          { key: 'Stovetops', value: 'All Types Including Induction' },
          { key: 'Oven Safe', value: 'Up to 180°C' },
        ],
        price: 5999,
        originalPrice: 9999,
        stock: 75,
        sku: 'CK-SET-10PC-GY',
        barcode: '8901234567903',
        category: categories[2]._id,
        brand: 'Prestige',
        images: [
          { url: 'https://m.media-amazon.com/images/I/71X5Q5Q5Q5L._SL1500_.jpg', isPrimary: true },
        ],
        ratings: 4.4,
        numReviews: 2345,
        isBestSeller: true,
        freeDelivery: true,
        tags: ['cookware', 'kitchen', 'non-stick', 'set', 'prestige'],
        sellCount: 12000,
      },
      {
        name: 'Smart Air Purifier with HEPA Filter',
        description: 'Advanced air purifier with true HEPA filter that captures 99.97% of airborne particles. Smart sensors automatically adjust fan speed. Covers rooms up to 500 sq ft. Quiet operation at just 24dB.',
        features: ['True HEPA Filter', 'Smart Auto Mode', '500 sq ft Coverage', '24dB Quiet', 'WiFi Connected'],
        specifications: [
          { key: 'Filter', value: 'True HEPA + Activated Carbon' },
          { key: 'Coverage', value: '500 sq ft' },
          { key: 'CADR', value: '300 m³/h' },
          { key: 'Noise Level', value: '24-50dB' },
          { key: 'Power', value: '50W' },
          { key: 'Connectivity', value: 'WiFi, Alexa, Google Home' },
        ],
        price: 24999,
        originalPrice: 32999,
        stock: 30,
        sku: 'AP-HEPA-SMART-WH',
        barcode: '8901234567904',
        category: categories[2]._id,
        brand: 'Philips',
        images: [
          { url: 'https://m.media-amazon.com/images/I/71X5Q5Q5Q5L._SL1500_.jpg', isPrimary: true },
        ],
        ratings: 4.6,
        numReviews: 890,
        isFeatured: true,
        isNewArrival: true,
        freeDelivery: true,
        tags: ['air purifier', 'hepa', 'smart', 'philips', 'home'],
        sellCount: 3500,
      },

      // === BOOKS ===
      {
        name: 'Atomic Habits: An Easy & Proven Way to Build Good Habits',
        description: 'The #1 New York Times bestseller. James Clear reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.',
        features: ['#1 NYT Bestseller', 'Practical Strategies', 'Proven Framework', 'Real-Life Examples', 'Actionable Steps'],
        specifications: [
          { key: 'Author', value: 'James Clear' },
          { key: 'Format', value: 'Paperback' },
          { key: 'Pages', value: '320' },
          { key: 'Publisher', value: 'Penguin Random House' },
          { key: 'Language', value: 'English' },
          { key: 'ISBN', value: '978-0735211292' },
        ],
        price: 499,
        originalPrice: 799,
        stock: 500,
        sku: 'BK-ATOMIC-HABITS',
        barcode: '8901234567905',
        category: categories[3]._id,
        brand: 'Penguin',
        images: [
          { url: 'https://m.media-amazon.com/images/I/81wgcld4wxL._AC_UY218_.jpg', isPrimary: true },
        ],
        ratings: 4.8,
        numReviews: 56789,
        isBestSeller: true,
        isTrending: true,
        freeDelivery: true,
        tags: ['book', 'self-help', 'habits', 'bestseller', 'psychology'],
        sellCount: 100000,
      },
      {
        name: 'The Alchemist - 25th Anniversary Edition',
        description: 'Paulo Coelho\'s enchanting novel has inspired a devoted following around the world. This story, dazzling in its powerful simplicity and soul-stirring wisdom, is about an Andalusian shepherd boy named Santiago.',
        features: ['25th Anniversary Edition', 'International Bestseller', 'Inspirational Story', 'Beautiful Cover', 'Foreword by Author'],
        specifications: [
          { key: 'Author', value: 'Paulo Coelho' },
          { key: 'Format', value: 'Paperback' },
          { key: 'Pages', value: '208' },
          { key: 'Publisher', value: 'HarperOne' },
          { key: 'Language', value: 'English' },
          { key: 'ISBN', value: '978-0062315007' },
        ],
        price: 399,
        originalPrice: 599,
        stock: 400,
        sku: 'BK-ALCHEMIST-25',
        barcode: '8901234567906',
        category: categories[3]._id,
        brand: 'HarperCollins',
        images: [
          { url: 'https://m.media-amazon.com/images/I/71aFt4+OTOL._AC_UY218_.jpg', isPrimary: true },
        ],
        ratings: 4.7,
        numReviews: 34567,
        isBestSeller: true,
        freeDelivery: true,
        tags: ['book', 'fiction', 'classic', 'inspirational', 'philosophy'],
        sellCount: 80000,
      },

      // === SPORTS & FITNESS ===
      {
        name: 'Smart Fitness Tracker with Heart Rate Monitor',
        description: 'Advanced fitness tracker with 24/7 heart rate monitoring, SpO2 tracking, sleep analysis, and 20+ workout modes. 1.4" AMOLED display, 14-day battery life, and water resistant to 50m.',
        features: ['24/7 Heart Rate', 'SpO2 Tracking', '20+ Workout Modes', '1.4" AMOLED', '14-Day Battery'],
        specifications: [
          { key: 'Display', value: '1.4" AMOLED' },
          { key: 'Battery', value: '14 Days' },
          { key: 'Water Resistance', value: '5 ATM (50m)' },
          { key: 'Sensors', value: 'HR, SpO2, Accelerometer, Gyro' },
          { key: 'Connectivity', value: 'Bluetooth 5.2' },
          { key: 'Compatibility', value: 'iOS 12+, Android 6+' },
        ],
        price: 3999,
        originalPrice: 7999,
        stock: 120,
        sku: 'FT-SMART-HR-BK',
        barcode: '8901234567907',
        category: categories[4]._id,
        brand: 'Mi',
        images: [
          { url: 'https://m.media-amazon.com/images/I/71X5Q5Q5Q5L._SL1500_.jpg', isPrimary: true },
        ],
        colors: [{ name: 'Black', hex: '#000000', stock: 50 }, { name: 'Navy', hex: '#000080', stock: 35 }, { name: 'Teal', hex: '#008080', stock: 35 }],
        ratings: 4.3,
        numReviews: 4567,
        isBestSeller: true,
        freeDelivery: true,
        tags: ['fitness tracker', 'smart band', 'heart rate', 'mi', 'fitness'],
        sellCount: 25000,
      },
      {
        name: 'Professional Yoga Mat - Premium TPE',
        description: 'Premium TPE yoga mat with excellent grip and cushioning. Non-slip surface on both sides, eco-friendly material, and comes with carrying strap. Perfect for yoga, pilates, and stretching.',
        features: ['Premium TPE Material', 'Non-Slip Both Sides', 'Eco-Friendly', 'Carrying Strap', '6mm Thickness'],
        specifications: [
          { key: 'Material', value: 'TPE (Eco-Friendly)' },
          { key: 'Dimensions', value: '183cm x 68cm' },
          { key: 'Thickness', value: '6mm' },
          { key: 'Weight', value: '1.2 kg' },
          { key: 'Color', value: 'Purple' },
        ],
        price: 1499,
        originalPrice: 2499,
        stock: 200,
        sku: 'YOGA-MAT-TPE-PP',
        barcode: '8901234567908',
        category: categories[4]._id,
        brand: 'ProQuest',
        images: [
          { url: 'https://m.media-amazon.com/images/I/71X5Q5Q5Q5L._SL1500_.jpg', isPrimary: true },
        ],
        colors: [{ name: 'Purple', hex: '#800080', stock: 60 }, { name: 'Blue', hex: '#0000FF', stock: 50 }, { name: 'Green', hex: '#008000', stock: 50 }, { name: 'Black', hex: '#000000', stock: 40 }],
        ratings: 4.4,
        numReviews: 2345,
        isFeatured: true,
        freeDelivery: true,
        tags: ['yoga mat', 'fitness', 'exercise', 'tpe', 'non-slip'],
        sellCount: 15000,
      },

      // === BEAUTY & PERSONAL CARE ===
      {
        name: 'Vitamin C Serum 20% with Hyaluronic Acid',
        description: 'Powerful Vitamin C serum with 20% L-Ascorbic Acid, Hyaluronic Acid, and Vitamin E. Brightens skin, reduces dark spots, and boosts collagen production. Suitable for all skin types.',
        features: ['20% Vitamin C', 'Hyaluronic Acid', 'Vitamin E', 'Brightening', 'Anti-Aging'],
        specifications: [
          { key: 'Active Ingredients', value: '20% L-Ascorbic Acid, HA, Vitamin E' },
          { key: 'Volume', value: '30ml' },
          { key: 'Skin Type', value: 'All Skin Types' },
          { key: 'Usage', value: 'Apply 3-4 drops morning & night' },
          { key: 'Shelf Life', value: '6 months after opening' },
        ],
        price: 849,
        originalPrice: 1499,
        stock: 300,
        sku: 'VITC-SERUM-30ML',
        barcode: '8901234567909',
        category: categories[5]._id,
        brand: 'The Ordinary',
        images: [
          { url: 'https://m.media-amazon.com/images/I/71X5Q5Q5Q5L._SL1500_.jpg', isPrimary: true },
        ],
        ratings: 4.5,
        numReviews: 12345,
        isBestSeller: true,
        freeDelivery: true,
        tags: ['vitamin c', 'serum', 'skincare', 'brightening', 'anti-aging'],
        sellCount: 50000,
      },
      {
        name: 'Professional Hair Dryer with Diffuser',
        description: '2000W professional hair dryer with ionic technology for frizz-free styling. Includes concentrator and diffuser attachments. 3 heat settings, 2 speed settings, and cool shot button.',
        features: ['2000W Motor', 'Ionic Technology', 'Diffuser Included', '3 Heat Settings', 'Cool Shot Button'],
        specifications: [
          { key: 'Power', value: '2000W' },
          { key: 'Technology', value: 'Ionic' },
          { key: 'Attachments', value: 'Concentrator + Diffuser' },
          { key: 'Settings', value: '3 Heat, 2 Speed, Cool Shot' },
          { key: 'Cord Length', value: '2.5m' },
          { key: 'Weight', value: '550g' },
        ],
        price: 2499,
        originalPrice: 3999,
        stock: 80,
        sku: 'HDR-PRO-2000-BK',
        barcode: '8901234567910',
        category: categories[5]._id,
        brand: 'Philips',
        images: [
          { url: 'https://m.media-amazon.com/images/I/71X5Q5Q5Q5L._SL1500_.jpg', isPrimary: true },
        ],
        ratings: 4.3,
        numReviews: 3456,
        isFeatured: true,
        tags: ['hair dryer', 'professional', 'ionic', 'philips', 'beauty'],
        sellCount: 18000,
      },

      // === TOYS & GAMES ===
      {
        name: 'LEGO Star Wars Millennium Falcon 75192',
        description: 'The ultimate LEGO Star Wars building set! This 7541-piece UCS Millennium Falcon is the largest and most detailed version yet. Features detailed interior, removable hull panels, and 7 minifigures.',
        features: ['7541 Pieces', 'UCS Edition', '7 Minifigures', 'Detailed Interior', 'Display Stand'],
        specifications: [
          { key: 'Pieces', value: '7541' },
          { key: 'Age Range', value: '16+' },
          { key: 'Dimensions', value: '84cm x 56cm x 21cm' },
          { key: 'Minifigures', value: '7' },
          { key: 'Series', value: 'Ultimate Collector Series' },
        ],
        price: 84999,
        originalPrice: 99999,
        stock: 10,
        sku: 'LEGO-MF-75192',
        barcode: '8901234567911',
        category: categories[6]._id,
        brand: 'LEGO',
        images: [
          { url: 'https://m.media-amazon.com/images/I/71X5Q5Q5Q5L._SL1500_.jpg', isPrimary: true },
        ],
        ratings: 4.9,
        numReviews: 1234,
        isFeatured: true,
        freeDelivery: true,
        tags: ['lego', 'star wars', 'millennium falcon', 'building set', 'collector'],
        sellCount: 500,
      },
      {
        name: 'Nintendo Switch OLED - White',
        description: 'The Nintendo Switch OLED model features a vibrant 7-inch OLED screen, wide adjustable stand, enhanced audio, and 64GB internal storage. Play at home on TV or on-the-go.',
        features: ['7" OLED Screen', '64GB Storage', 'Wide Adjustable Stand', 'Enhanced Audio', 'TV + Handheld Modes'],
        specifications: [
          { key: 'Display', value: '7" OLED 1280x720' },
          { key: 'Storage', value: '64GB (Expandable)' },
          { key: 'Battery', value: '4.5-9 Hours' },
          { key: 'Connectivity', value: 'WiFi, Bluetooth 4.1' },
          { key: 'Weight', value: '420g' },
          { key: 'TV Output', value: 'Up to 1080p via Dock' },
        ],
        price: 31999,
        originalPrice: 34999,
        stock: 25,
        sku: 'NS-OLED-WH',
        barcode: '8901234567912',
        category: categories[6]._id,
        brand: 'Nintendo',
        images: [
          { url: 'https://m.media-amazon.com/images/I/71X5Q5Q5Q5L._SL1500_.jpg', isPrimary: true },
        ],
        colors: [{ name: 'White', hex: '#FFFFFF', stock: 15 }, { name: 'Neon Blue/Red', hex: '#0000FF', stock: 10 }],
        ratings: 4.7,
        numReviews: 5678,
        isBestSeller: true,
        isTrending: true,
        freeDelivery: true,
        tags: ['nintendo', 'switch', 'gaming', 'console', 'oled'],
        sellCount: 10000,
      },

      // === AUTOMOTIVE ===
      {
        name: 'Premium Car Dash Camera 4K',
        description: 'Ultra HD 4K dash cam with Sony STARVIS sensor for crystal clear footage day and night. Features GPS tracking, parking mode, wide angle 170° lens, and WiFi connectivity for easy video transfer.',
        features: ['4K Ultra HD', 'Sony STARVIS Sensor', 'GPS Tracking', 'Parking Mode', '170° Wide Angle'],
        specifications: [
          { key: 'Resolution', value: '4K 2160p @30fps' },
          { key: 'Sensor', value: 'Sony STARVIS IMX415' },
          { key: 'Lens', value: '170° Wide Angle' },
          { key: 'Storage', value: 'Up to 256GB MicroSD' },
          { key: 'GPS', value: 'Built-in' },
          { key: 'Connectivity', value: 'WiFi 5GHz' },
        ],
        price: 12999,
        originalPrice: 17999,
        stock: 45,
        sku: 'DASH-4K-SONY-BK',
        barcode: '8901234567913',
        category: categories[7]._id,
        brand: '70mai',
        images: [
          { url: 'https://m.media-amazon.com/images/I/71X5Q5Q5Q5L._SL1500_.jpg', isPrimary: true },
        ],
        ratings: 4.5,
        numReviews: 2345,
        isFeatured: true,
        isNewArrival: true,
        freeDelivery: true,
        tags: ['dash cam', 'car', '4k', 'gps', 'parking mode'],
        sellCount: 6000,
      },
      {
        name: 'Car Seat Cover Set - Premium Leatherette',
        description: 'Premium leatherette car seat cover set for front and rear seats. Universal fit for most cars. Features quilted design, side airbag compatibility, and easy installation. 5-year warranty.',
        features: ['Premium Leatherette', 'Universal Fit', 'Airbag Compatible', 'Quilted Design', '5-Year Warranty'],
        specifications: [
          { key: 'Material', value: 'Premium Leatherette' },
          { key: 'Fit', value: 'Universal (Most Cars)' },
          { key: 'Pieces', value: '5 (2 Front + 1 Rear + 2 Headrest)' },
          { key: 'Features', value: 'Airbag Compatible, Quilted' },
          { key: 'Warranty', value: '5 Years' },
          { key: 'Installation', value: 'Easy DIY, Straps Included' },
        ],
        price: 4999,
        originalPrice: 7999,
        stock: 60,
        sku: 'CVR-LEATHER-BK',
        barcode: '8901234567914',
        category: categories[7]._id,
        brand: 'AutoFurnish',
        images: [
          { url: 'https://m.media-amazon.com/images/I/71X5Q5Q5Q5L._SL1500_.jpg', isPrimary: true },
        ],
        colors: [{ name: 'Black', hex: '#000000', stock: 25 }, { name: 'Beige', hex: '#F5F5DC', stock: 20 }, { name: 'Brown', hex: '#8B4513', stock: 15 }],
        ratings: 4.2,
        numReviews: 1567,
        isBestSeller: true,
        freeDelivery: true,
        tags: ['car seat covers', 'leather', 'auto', 'interior', 'accessories'],
        sellCount: 9000,
      },

      // === ELECTRONICS - Cameras ===
      {
        name: 'Canon EOS R8 Mirrorless Camera',
        description: 'Compact full-frame mirrorless camera with 24.2MP sensor, DIGIC X processor, and advanced autofocus for both photo and video creators.',
        features: ['24.2MP Full-frame', 'DIGIC X Processor', 'Dual Pixel AF', '4K 60fps Video', 'Vari-angle Touchscreen'],
        specifications: [
          { key: 'Sensor', value: '24.2MP Full-frame CMOS' },
          { key: 'Processor', value: 'DIGIC X' },
          { key: 'Video', value: '4K 60fps' },
          { key: 'ISO', value: '100-51200' },
          { key: 'Autofocus', value: 'Dual Pixel CMOS AF II' },
          { key: 'Weight', value: '461g' },
        ],
        price: 159999,
        originalPrice: 179999,
        stock: 25,
        sku: 'CAN-EOS-R8-BK',
        barcode: '8901234567915',
        category: electronicsSubs[3]._id,
        brand: 'Canon',
        images: [
          { url: 'https://m.media-amazon.com/images/I/81sV6BGM5nL._AC_SL1500_.jpg', isPrimary: true },
        ],
        ratings: 4.7,
        numReviews: 789,
        isFeatured: true,
        isNewArrival: true,
        freeDelivery: true,
        tags: ['camera', 'mirrorless', 'canon', 'photography', '4k'],
        sellCount: 4200,
      },

      // === FASHION - Accessories ===
      {
        name: 'Ray-Ban Erika Classic Sunglasses',
        description: 'Classic round sunglasses with gradient lenses and a comfortable nylon frame. Perfect for everyday style with UV protection and timeless appeal.',
        features: ['Gradient Lenses', 'Nylon Frame', 'UV Protection', 'Silicone Nose Pads', 'Lightweight Design'],
        specifications: [
          { key: 'Lens', value: 'Gradient' },
          { key: 'Frame', value: 'Nylon' },
          { key: 'UV Protection', value: '100% UV400' },
          { key: 'Fit', value: 'Unisex' },
          { key: 'Color', value: 'Matte Black' },
          { key: 'Weight', value: '21g' },
        ],
        price: 6999,
        originalPrice: 9999,
        stock: 90,
        sku: 'RB-ERIKA-CLS-BK',
        barcode: '8901234567916',
        category: fashionSubs[4]._id,
        brand: 'Ray-Ban',
        images: [
          { url: 'https://static.ray-ban.com/Images/ERIKA__RB4171_601_71_55.png', isPrimary: true },
        ],
        ratings: 4.6,
        numReviews: 1456,
        isFeatured: true,
        isTrending: true,
        freeDelivery: true,
        tags: ['sunglasses', 'ray-ban', 'accessories', 'uv protection', 'fashion'],
        sellCount: 6200,
      },

      // === HOME & KITCHEN - Smart Appliances ===
      {
        name: 'Smart Robot Vacuum Cleaner with Mopping',
        description: 'Intelligent robot vacuum with app control, mapping, automatic charging, and wet mopping mode for hands-free cleaning across hard floors and low-pile carpets.',
        features: ['App Control', 'Smart Mapping', 'Self-Charging', 'Wet Mopping', 'Voice Assistant Support'],
        specifications: [
          { key: 'Suction', value: '3000Pa' },
          { key: 'Battery', value: '5200mAh' },
          { key: 'Runtime', value: '120 minutes' },
          { key: 'Dustbin', value: '600ml' },
          { key: 'Water Tank', value: '350ml' },
          { key: 'Navigation', value: 'Lidar + SLAM' },
        ],
        price: 17999,
        originalPrice: 22999,
        stock: 45,
        sku: 'RBV-ROBO-MOP-2024',
        barcode: '8901234567917',
        category: categories[2]._id,
        brand: 'RoboClean',
        images: [
          { url: 'https://m.media-amazon.com/images/I/71X5Q5Q5Q5L._SL1500_.jpg', isPrimary: true },
        ],
        ratings: 4.4,
        numReviews: 2340,
        isNewArrival: true,
        freeDelivery: true,
        tags: ['robot vacuum', 'smart home', 'cleaning', 'mopping', 'home appliances'],
        sellCount: 5400,
      },
    ];

    const products = await Product.create(rawProducts);
    console.log(`${products.length} products created`.green);

    // Create Coupons
    const coupons = await Coupon.create([
      {
        code: 'WELCOME20',
        description: '20% off for new customers',
        discountType: 'percentage',
        discountValue: 20,
        maxDiscount: 500,
        minOrderValue: 999,
        maxUsageCount: 1000,
        perUserLimit: 1,
        isActive: true,
        isFirstOrder: true,
        startDate: new Date('2024-01-01'),
        endDate: new Date('2025-12-31'),
      },
      {
        code: 'SAVE500',
        description: 'Flat ₹500 off on orders above ₹2999',
        discountType: 'fixed',
        discountValue: 500,
        minOrderValue: 2999,
        maxUsageCount: 500,
        perUserLimit: 2,
        isActive: true,
        startDate: new Date('2024-01-01'),
        endDate: new Date('2025-12-31'),
      },
      {
        code: 'FREEDEL',
        description: 'Free delivery on your next order',
        discountType: 'fixed',
        discountValue: 40,
        minOrderValue: 0,
        maxUsageCount: 2000,
        perUserLimit: 1,
        isActive: true,
        startDate: new Date('2024-01-01'),
        endDate: new Date('2025-12-31'),
      },
      {
        code: 'SUMMER50',
        description: '50% off on summer collection (max ₹1000)',
        discountType: 'percentage',
        discountValue: 50,
        maxDiscount: 1000,
        minOrderValue: 1999,
        maxUsageCount: 300,
        perUserLimit: 1,
        isActive: true,
        startDate: new Date('2024-03-01'),
        endDate: new Date('2024-06-30'),
      },
      {
        code: 'FESTIVE15',
        description: '15% off on all products',
        discountType: 'percentage',
        discountValue: 15,
        maxDiscount: 2000,
        minOrderValue: 999,
        maxUsageCount: 1000,
        perUserLimit: 3,
        isActive: true,
        startDate: new Date('2024-10-01'),
        endDate: new Date('2025-01-15'),
      },
    ]);

    console.log(`${coupons.length} coupons created`.green);
    console.log('\n========================================'.green);
    console.log('✅ SEED DATA CREATED SUCCESSFULLY!'.green.bold);
    console.log('========================================'.green);
    console.log('\n📧 Admin Login: admin@shophub.com / Admin@123'.cyan);
    console.log('📧 User Login:  user@shophub.com / User@123'.cyan);
    console.log(`\n📦 Products: ${products.length}`.cyan);
    console.log(`📁 Categories: ${categories.length}`.cyan);
    console.log(`🏷️ Coupons: ${coupons.length}`.cyan);
    console.log('\n========================================\n'.green);
  } catch (error) {
    console.error('Seed error:'.red, error);
    throw error;
  }
};

if (require.main === module) {
  seedData()
    .then(() => process.exit(0))
    .catch(() => process.exit(1));
}

module.exports = seedData;